#!/bin/bash
set -e

cat <<EOF
NameVirtualHost *:80

<VirtualHost *:80>
     ServerAdmin kngnm@bsc.coop
     ServerName ${HOSTNAME}
     ServerAlias www.${HOSTNAME}
     # DocumentRoot /var/www/html/
     Redirect permanent / https://${HOSTNAME}/
     ErrorLog logs/error_log
     CustomLog logs/access_log combined
</VirtualHost>

NameVirtualHost *:443

WSGISocketPrefix run/wsgi

<VirtualHost *:443>
     ServerAdmin kngnm@bsc.coop
     ServerName ${HOSTNAME}
     ServerAlias www.${HOSTNAME}
     # DocumentRoot /var/www/html/
     ErrorLog logs/error_log
     CustomLog logs/access_log combined

     WSGIDaemonProcess ${HOSTNAME}
     WSGIProcessGroup ${HOSTNAME}

     WSGIScriptAlias / /var/www/farnsworth/farnsworth/wsgi.py

     Alias /static/ /var/www/farnsworth/static/

     # SSLEngine on
     # SSLCertificateFile /etc/pki/tls/certs/${HOSTNAME}.crt
     # SSLCertificateKeyFile /etc/pki/tls/private/${HOSTNAME}.key
     # SSLCertificateChainFile /etc/pki/tls/certs/sub.class1.server.ca.pem
</VirtualHost>
EOF > /etc/httpd/conf.d/vhost.conf

cd /var/www/farnsworth

su - apache -c "cat" <<EOF
SECRET_KEY = "$(openssl rand -base64 50)"
HOUSE_NAME = "Kingman Hall"
SHORT_HOUSE_NAME = "Kingman"
HOUSE_ABBREV = "kng"
SITE_DOMAIN = "${HOSTNAME}"
POSTGRES_PASSWORD = "${POSTGRESQL_PASS}"
EOF > farnsworth/house_settings.py

su - apache -c "./manage.py syncdb"
su - apache -c "./manage.py collectstatic"
su - apache -c "./manage.py test"
#./manage.py migrate

/usr/sbin/apache2ctl -D FOREGROUND
