#!/bin/bash
set -e

FARNSWORTH=/opt/apps/farnsworth
KEYS_FOLDER=/opt/apps/keys
UWSGI_INI=/opt/apps/uwsgi.ini
SUPERVISORD_CONF=/opt/apps/supervisord.conf

cat > ${UWSGI_INI} <<EOF
[uwsgi]
master = true
enable-threads = true
processes = 4
shared-socket = :80
uid = www-data
gid = www-data
chdir = ${FARNSWORTH}
module = farnsworth.wsgi:application
env = DJANGO_SETTINGS_MODULE=farnsworth.settings
http = =0
static-map = /static=${FARNSWORTH}/static
route-uri = ^/internal/(.*)$ rewrite:/$1
EOF

if [ "xyes" = "x${ENABLE_SSL}" ] ; then
    cat >> ${UWSGI_INI} <<EOF
shared-socket = :443
https = =1,${KEYS_FOLDER}/${URL}.crt,${KEYS_FOLDER}/${URL}.key
route-if-not = equal:\${HTTPS};on redirect-permanent:https://${URL}\${REQUEST_URI}
EOF
fi

cat ${UWSGI_INI}

cd ${FARNSWORTH}

git checkout -b "${SHORT_HOUSE_NAME,,}" "origin/${SHORT_HOUSE_NAME,,}"

cat > farnsworth/house_settings.py <<EOF
SECRET_KEY = "$(openssl rand -base64 48)"
HOUSE_NAME = "${HOUSE_NAME}"
SHORT_HOUSE_NAME = "${SHORT_HOUSE_NAME}"
HOUSE_ABBREV = "${HOUSE_ABBREV}"
SITE_DOMAIN = "${URL}"
POSTGRES_PASSWORD = "${POSTGRESQL_PASS}"
EOF

echo "Collecting static files"
./manage.py collectstatic --noinput > /dev/null
echo "Creating database tables"
./manage.py syncdb --noinput > /dev/null
#./manage.py test
#./manage.py migrate

if [ "xyes" = "x${PRE_FILL}" ] ; then
    echo "Pre-filling database"
    farnsworth/pre_fill.py
fi

chown -R www-data:www-data .

echo "Running uwsgi server"
supervisord -n -c ${SUPERVISORD_CONF}
