#!/bin/bash
set -e

cat > /etc/httpd/conf.d/vhost.conf <<EOF
NameVirtualHost *:80

<VirtualHost *:80>
     ServerAdmin ${HOUSE_ABBREV}nm@bsc.coop
     ServerName ${HOSTNAME}
     ServerAlias www.${HOSTNAME}
     # DocumentRoot /var/www/html/
     Redirect permanent / https://${HOSTNAME}/
     ErrorLog logs/error_log
     CustomLog logs/access_log combined
</VirtualHost>

NameVirtualHost *:443

WSGISocketPrefix run/wsgi

<VirtualHost *:443>
     ServerAdmin kngnm@bsc.coop
     ServerName ${HOSTNAME}
     ServerAlias www.${HOSTNAME}
     # DocumentRoot /var/www/html/
     ErrorLog logs/error_log
     CustomLog logs/access_log combined

     WSGIDaemonProcess ${HOSTNAME}
     WSGIProcessGroup ${HOSTNAME}

     WSGIScriptAlias / /var/www/farnsworth/farnsworth/wsgi.py

     Alias /static/ /var/www/farnsworth/static/

     # SSLEngine on
     # SSLCertificateFile /etc/pki/tls/certs/${HOSTNAME}.crt
     # SSLCertificateKeyFile /etc/pki/tls/private/${HOSTNAME}.key
     # SSLCertificateChainFile /etc/pki/tls/certs/sub.class1.server.ca.pem
</VirtualHost>
EOF

cd /var/www/farnsworth

su - apache -c cat > farnsworth/house_settings.py <<EOF
SECRET_KEY = "$(openssl rand -base64 50)"
HOUSE_NAME = "${HOUSE_NAME}"
SHORT_HOUSE_NAME = "${SHORT_HOUSE_NAME}"
HOUSE_ABBREV = "${HOUSE_ABBREV}"
SITE_DOMAIN = "${HOSTNAME}"
POSTGRES_PASSWORD = "${POSTGRESQL_PASS}"
EOF

su - apache -c "./manage.py syncdb"
su - apache -c "./manage.py collectstatic"
su - apache -c "./manage.py test"
#su - apache -c "./manage.py migrate"

/usr/sbin/apache2 -D FOREGROUND
