#!/bin/bash
set -e

FARNSWORTH="/opt/apps/farnsworth"
KEYS_FOLDER="/opt/apps/keys"
UWSGI_INI="/opt/apps/uwsgi.ini"
UWSGI_PID="/opt/apps/uwsgi.pid"
SUPERVISORD_CONF="/opt/apps/supervisord.conf"
FARNSWORTH_CRON="/etc/cron.d/farnsworth.cron"

# Generate the uWSGI configuration
cat > "${UWSGI_INI}" <<EOF
[uwsgi]
master = true
#enable-threads = true
#processes = 4
shared-socket = :80
uid = www-data
gid = www-data
chdir = ${FARNSWORTH}
module = farnsworth.wsgi:application
env = DJANGO_SETTINGS_MODULE=farnsworth.local_settings
http = =0
static-map = /static=${FARNSWORTH}/static
route-uri = ^/internal/(.*)$ redirect:/\$1
pidfile = ${UWSGI_PID}
touch-reload = ${UWSGI_PID}
EOF

if [ "xyes" = "x${ENABLE_SSL}" ] ; then
    cat >> "${UWSGI_INI}" <<EOF
shared-socket = :443
https = =1,${KEYS_FOLDER}/public.crt,${KEYS_FOLDER}/private.key
plugins = router_redirect
route-if-not = equal:\${HTTPS};on redirect-permanent:https://\${HTTP_HOST}\${REQUEST_URI}
route-if = equal:\${HTTPS};on addheader:Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
EOF
fi

# Generate the cron file
cat > "${FARNSWORTH_CRON}" <<EOF
POSTGRESQL_PASS="${POSTGRESQL_PASS}"
DB_1_PORT_5432_TCP_ADDR="${DB_1_PORT_5432_TCP_ADDR}"
DB_1_PORT_5432_TCP_PORT="${DB_1_PORT_5432_TCP_PORT}"
*/5 * * * * root ${FARNSWORTH}/manage.py runcrons
EOF

chmod 644 "${FARNSWORTH_CRON}"

cd "${FARNSWORTH}"

# Check out a house-specific branch of the code if need be
if [ -n "${BRANCH}" ] ; then
    git checkout -b "${BRANCH}" "origin/${BRANCH}"
fi

# Update the repo
git pull

# Initialize the database, collect files, etc ...
echo "Collecting static files"
./manage.py collectstatic --noinput > /dev/null
echo "Creating database tables"
./manage.py migrate --noinput > /dev/null
echo "Updating search index"
./manage.py update_index > /dev/null

chown -R www-data:www-data .

# Run the uWSGI + cron daemons
echo "Running uWSGI server"
supervisord -n -c ${SUPERVISORD_CONF}
