#!/bin/bash
set -e

FARNSWORTH="/opt/apps/farnsworth"
KEYS_FOLDER="/opt/apps/keys"
UWSGI_INI="/opt/apps/uwsgi.ini"
UWSGI_PID="/opt/apps/uwsgi.pid"
SUPERVISORD_CONF="/opt/apps/supervisord.conf"
FARNSWORTH_CRON="/etc/cron.d/farnsworth.cron"
WORKERS=8

# Generate the uWSGI configuration
echo " *** creating ${UWSGI_INI} ***"
cat > "${UWSGI_INI}" <<EOF
[uwsgi]
master = true
#enable-threads = true
processes = ${WORKERS}
shared-socket = :80
uid = www-data
gid = www-data
chdir = ${FARNSWORTH}
module = farnsworth.wsgi:application
env = DJANGO_SETTINGS_MODULE=farnsworth.local_settings
http = =0
static-map = /static=${FARNSWORTH}/static
route-uri = ^/internal/(.*)$ redirect:/\$1
pidfile = ${UWSGI_PID}
touch-reload = ${UWSGI_PID}
EOF

if [ "xyes" = "x${ENABLE_SSL}" ] ; then
    echo "    *** enabling ssl ***"
    cat >> "${UWSGI_INI}" <<EOF
shared-socket = :443
https = =1,${KEYS_FOLDER}/public.crt,${KEYS_FOLDER}/private.key
plugins = router_redirect
spdy = 1
route-if-not = equal:\${HTTPS};on redirect-permanent:https://\${HTTP_HOST}\${REQUEST_URI}
route-if = equal:\${HTTPS};on addheader:Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
EOF
fi

# Generate the cron file
echo " *** creating ${FARNSWORTH_CRON} ***"
cat > "${FARNSWORTH_CRON}" <<EOF
DB_1_PORT_5432_TCP_ADDR="${DB_1_PORT_5432_TCP_ADDR}"
DB_1_PORT_5432_TCP_PORT="${DB_1_PORT_5432_TCP_PORT}"
*/5 * * * * root "${FARNSWORTH}/manage.py" runcrons
EOF

chmod 644 "${FARNSWORTH_CRON}"

cd "${FARNSWORTH}"

# Check out a house-specific branch of the code if need be
if [ -n "${BRANCH}" ] ; then
    echo " *** checking out alternate branch ${BRANCH} ***"
    git checkout -b "${BRANCH}" "origin/${BRANCH}"
fi

# Update the repo
echo " *** updating git repo ***"
git pull

# Initialize the database, collect files, etc ...
echo " *** collecting static files ***"
./manage.py collectstatic --noinput > /dev/null
echo " *** creating database tables ***"
./manage.py migrate --noinput > /dev/null
echo " *** updating search index ***"
./manage.py update_index --workers=${WORKERS} > /dev/null

echo " *** updating file permissions ***"
chown -R www-data:www-data .

# Run the uWSGI + cron daemons
echo " *** running uWSGI server ***"
supervisord -n -c "${SUPERVISORD_CONF}"
